apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: shaikmustafa/cycle
        ports:
        - containerPort: 80

